add web go and test
jinmukeji/jiujiantang-services pull request #12
Opened 2020-04-24 09:07 UTC by nichanglan

2020-04-24 09:28 UTC, Raikozyz submitted a review, later dismissed
LGTM

2020-04-24 09:32 UTC, skyjia requested changes

2020-04-24 09:32 UTC, skyjia commented on go.mod
> +	github.com/jinmukeji/gf-api2 v0.0.0-20200424031953-cd810283ffdc
引的包不对

2020-04-24 09:32 UTC, skyjia commented on go.mod
>  	github.com/jinmukeji/go-pkg v1.1.1
这个版本也不应该存在

2020-04-26 00:35 UTC, Raikozyz approved these changes
LGTM

2020-04-26 01:07 UTC, skyjia approved these changes
lgtm

2020-04-26 01:12 UTC, merged