update fqdn from com.jinmuhealth.srv to com.xima.srv
jinmukeji/jiujiantang-services pull request #4
Opened 2020-04-10 09:28 UTC by nichanglan

2020-04-10 09:29 UTC, Raikozyz submitted a review, later dismissed
LGTM

2020-04-10 09:33 UTC, skyjia requested changes

2020-04-10 09:33 UTC, skyjia commented on templates/README.md
>  | rest-api-l-v2  | com.jinmuhealth.api | API  | jm-app/web-rest-api-l-v2  |         |
漏了 .api 与 .web

2020-04-11 01:19 UTC, imxty approved these changes

2020-04-11 01:37 UTC, skyjia approved these changes
lgtm

2020-04-11 01:38 UTC, merged